from noisyart._cfg import DEFAULT_NOISYART_PATH, DEFAULT_SPLITS_FOLDER, DEFAULT_FEATS_FOLDER

DEFAULT_SPLIT_PATH = DEFAULT_NOISYART_PATH + DEFAULT_SPLITS_FOLDER + "/"
DEFAULT_FEATS_PATH = DEFAULT_NOISYART_PATH + DEFAULT_FEATS_FOLDER + "/"

#DEFAULT_IMGS_PATH = DEFAULT_DATASET_PATH + 'imgs/trainval_200/'
DEFAULT_IMGS_PATH = DEFAULT_NOISYART_PATH + 'imgs/trainval_200_r255_png/'

from PIL import Image

DEFAULT_SEED=42
DEFAULT_IM_RESIZE=255
DEFAULT_IM_CROP=224
DEFAULT_IM_INTERPOLATION=Image.BILINEAR
DEFAULT_IM_CHANNEL_MEAN=[0.485, 0.456, 0.406]
DEFAULT_IM_CHANNEL_STD=[0.229, 0.224, 0.225]


